# Generated by Django 5.0.4 on 2024-05-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestfeedback',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='guestfeedback',
            name='message',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tempguestfeedback',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='tempguestfeedback',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
