# Generated by Django 5.0.4 on 2024-05-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_guestfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestfeedback',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
