# Generated by Django 5.0.4 on 2024-05-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_application_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestfeedback',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
