# Generated by Django 5.0.4 on 2024-05-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_favorite_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('open', 'Otwarta'), ('closed', 'Zamknięta')], default='open', max_length=20),
        ),
    ]
