# Generated by Django 5.0.4 on 2024-05-17 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_guestfeedback_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestfeedback',
            name='verification_token',
        ),
    ]
