# Generated by Django 5.0.4 on 2024-05-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('submitted', 'Złożone'), ('reviewed', 'Przejrzane'), ('accepted', 'Zaakceptowane'), ('rejected', 'Odrzucone')], default='submitted', max_length=20),
        ),
    ]
