# Generated by Django 5.0.4 on 2024-05-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('content', models.TextField(verbose_name='Zawartość')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('role', models.CharField(choices=[('candidate', 'Kandydat'), ('client', 'Klient'), ('recruiter', 'Rekruter')], max_length=50, verbose_name='Rola')),
            ],
        ),
    ]
