# Generated by Django 5.0.4 on 2024-05-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='Zawartość'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data dodania'),
        ),
        migrations.AlterField(
            model_name='news',
            name='role',
            field=models.CharField(choices=[('candidate', 'Kandydat'), ('client', 'Klient'), ('recruiter', 'Rekruter')], max_length=50, verbose_name='Rola'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tytuł'),
        ),
    ]
