# Generated by Django 5.0.4 on 2024-04-30 14:12

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='adres email')),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('role', models.CharField(blank=True, choices=[('candidate', 'Kandydat'), ('employer', 'Klient'), ('recruiter', 'Recruiter')], max_length=10, null=True, verbose_name='Rola')),
            ],
            options={
                'verbose_name': 'użytkownik',
                'verbose_name_plural': 'użytkownicy',
            },
        ),
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='candidate_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(default='', max_length=100, verbose_name='Imię')),
                ('last_name', models.CharField(default='', max_length=100, verbose_name='Nazwisko')),
                ('phone_number', models.CharField(default='', max_length=15, verbose_name='Numer telefonu')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Zdjęcie')),
                ('location', models.CharField(default='', max_length=100, verbose_name='Lokalizacja')),
                ('bio', models.TextField(default='', verbose_name='Biografia')),
                ('date_of_birth', models.DateField(blank=True, default=datetime.date.today, verbose_name='Data urodzenia')),
                ('skills', models.TextField(default='', verbose_name='Umiejętności')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='client_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(default='', max_length=15, verbose_name='Numer telefonu')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Zdjęcie')),
                ('location', models.CharField(default='', max_length=100, verbose_name='Lokalizacja')),
                ('bio', models.TextField(default='', verbose_name='Biografia')),
                ('company_name', models.CharField(max_length=100, verbose_name='Nazwa firmy')),
                ('industry', models.CharField(default='', max_length=50, verbose_name='Branża')),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='recruiter_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(default='', max_length=100, verbose_name='Imię')),
                ('last_name', models.CharField(default='', max_length=100, verbose_name='Nazwisko')),
                ('phone_number', models.CharField(default='', max_length=15, verbose_name='Numer telefonu')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Zdjęcie')),
                ('location', models.CharField(default='', max_length=100, verbose_name='Lokalizacja')),
                ('bio', models.TextField(default='', verbose_name='Biografia')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('description', models.TextField(verbose_name='Opis')),
                ('priority', models.CharField(choices=[('low', 'Niski'), ('medium', 'Średni'), ('high', 'Wysoki')], max_length=50, verbose_name='Priorytet')),
                ('due_date', models.DateField(default=datetime.date.today, verbose_name='Termin wykonania')),
                ('status', models.CharField(choices=[('open', 'Otwarte'), ('in_progress', 'W trakcie realizacji'), ('completed', 'Zakończone')], max_length=50, verbose_name='Status')),

            ],
        ),
    ]
