# Generated by Django 5.0.4 on 2024-05-16 20:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='adres e-mail')),
                ('is_active', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, max_length=64, null=True)),
                ('role', models.CharField(choices=[('candidate', 'Kandydat'), ('client', 'Klient'), ('recruiter', 'Rekruter')], max_length=10, verbose_name='Rola')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'użytkownik',
                'verbose_name_plural': 'użytkownicy',
                'permissions': [('can_view_dashboard', 'Może przeglądać pulpit nawigacyjny')],
            },
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='candidate_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Imię')),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nazwisko')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Podaj poprawny numer telefonu', regex='^\\+?1?\\d{9,15}$')], verbose_name='Numer telefonu')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Zdjęcie')),
                ('location', models.CharField(max_length=100, verbose_name='Lokalizacja')),
                ('bio', models.TextField(verbose_name='Biografia')),
                ('date_of_birth', models.DateField(null=True, verbose_name='Data urodzenia')),
                ('skills', models.TextField(verbose_name='Umiejętności')),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='client_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Podaj poprawny numer telefonu', regex='^\\+?1?\\d{9,15}$')], verbose_name='Numer telefonu')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Zdjęcie')),
                ('location', models.CharField(max_length=100, verbose_name='Lokalizacja')),
                ('bio', models.TextField(verbose_name='Biografia')),
                ('company_name', models.CharField(max_length=100, verbose_name='Nazwa firmy')),
                ('industry', models.CharField(max_length=50, verbose_name='Branża')),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='recruiter_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Imię')),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nazwisko')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Podaj poprawny numer telefonu', regex='^\\+?1?\\d{9,15}$')], verbose_name='Numer telefonu')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Zdjęcie')),
                ('location', models.CharField(max_length=100, verbose_name='Lokalizacja')),
                ('bio', models.TextField(verbose_name='Biografia')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('description', models.TextField(verbose_name='Opis')),
                ('priority', models.CharField(choices=[('low', 'Niski'), ('medium', 'Średni'), ('high', 'Wysoki')], max_length=50, verbose_name='Priorytet')),
                ('due_date', models.DateField(verbose_name='Termin wykonania')),
                ('status', models.CharField(choices=[('open', 'Otwarte'), ('in_progress', 'W trakcie realizacji'), ('completed', 'Zakończone')], default='open', max_length=50, verbose_name='Status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Utworzone przez')),
            ],
        ),
    ]
