# Generated by Django 5.0.4 on 2024-05-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Otwarte'), ('in_progress', 'W trakcie realizacji'), ('completed', 'Zakończone')], default='open', max_length=50, verbose_name='Status'),
        ),
    ]
