# Generated by Django 5.0.4 on 2024-04-30 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_applicantprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='bio',
            field=models.TextField(default='', verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Data urodzenia'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='location',
            field=models.CharField(default='', max_length=100, verbose_name='Lokalizacja'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='phone_number',
            field=models.CharField(default='', max_length=15, verbose_name='Numer telefonu'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='skills',
            field=models.TextField(default='', verbose_name='Umiejętności'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='bio',
            field=models.TextField(default='', verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='industry',
            field=models.CharField(default='', max_length=50, verbose_name='Branża'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='location',
            field=models.CharField(default='', max_length=100, verbose_name='Lokalizacja'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='phone_number',
            field=models.CharField(default='', max_length=15, verbose_name='Numer telefonu'),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='bio',
            field=models.TextField(default='', verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='location',
            field=models.CharField(default='', max_length=100, verbose_name='Lokalizacja'),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='phone_number',
            field=models.CharField(default='', max_length=15, verbose_name='Numer telefonu'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Termin wykonania'),
        ),
    ]
