# Generated by Django 5.0.4 on 2024-05-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Data urodzenia'),
        ),
    ]
