# Generated by Django 5.0.4 on 2024-04-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_task_created_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployerProfile',
            new_name='ClientProfile',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('candidate', 'Kandydat'), ('client', 'Klient'), ('recruiter', 'Recruiter')], max_length=10, null=True, verbose_name='Rola'),
        ),
    ]
