# Generated by Django 5.0.4 on 2024-04-30 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_employerprofile_clientprofile_alter_user_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicantProfile',
            new_name='CandidateProfile',
        ),
    ]
