# Generated by Django 5.0.4 on 2024-05-16 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('description', models.TextField(max_length=500, verbose_name='Opis')),
                ('requirements', models.TextField(max_length=300, verbose_name='Wymagania')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('status', models.CharField(choices=[('pending', 'Oczekujące'), ('processing', 'W trakcie realizacji'), ('completed', 'Zakończone')], default='pending', max_length=20, verbose_name='Status')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requests', to=settings.AUTH_USER_MODEL, verbose_name='Pracodawca')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruited_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Rekruter')),
            ],
            options={
                'verbose_name': 'Zapotrzebowanie na pracę',
                'verbose_name_plural': 'Zapotrzebowania na pracę',
            },
        ),
        migrations.CreateModel(
            name='JobRequestStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_status', models.CharField(choices=[('pending', 'Oczekujące'), ('processing', 'W trakcie realizacji'), ('completed', 'Zakończone')], max_length=20, verbose_name='Nowy status')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Data aktualizacji')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Wiadomość')),
                ('job_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='requests.jobrequest', verbose_name='Aktualizacja statusu zapotrzebowania na pracę')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Zaktualizowane przez')),
            ],
            options={
                'verbose_name': 'Aktualizacja statusu zapotrzebowania',
                'verbose_name_plural': 'Aktualizacje statusów zapotrzebowania',
            },
        ),
        migrations.CreateModel(
            name='FavoriteRecruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='accounts.recruiterprofile', verbose_name='Ulubiony rekruter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_recruiters', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Ulubiony rekruter',
                'verbose_name_plural': 'Ulubieni rekruterzy',
                'unique_together': {('user', 'recruiter')},
            },
        ),
    ]
