# Generated by Django 5.0.4 on 2024-05-13 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_favoriterecruiter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriterecruiter',
            options={'verbose_name': 'Ulubiony rekruter', 'verbose_name_plural': 'Ulubieni rekruterzy'},
        ),
        migrations.AlterModelOptions(
            name='jobrequest',
            options={'verbose_name': 'Zapotrzebowanie na pracę', 'verbose_name_plural': 'Zapotrzebowania na pracę'},
        ),
        migrations.AlterModelOptions(
            name='jobrequeststatusupdate',
            options={'verbose_name': 'Aktualizacja statusu zapotrzebowania', 'verbose_name_plural': 'Aktualizacje statusów zapotrzebowania'},
        ),
        migrations.AlterField(
            model_name='favoriterecruiter',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to=settings.AUTH_USER_MODEL, verbose_name='Ulubiony rekruter'),
        ),
        migrations.AlterField(
            model_name='favoriterecruiter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_recruiters', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requests', to=settings.AUTH_USER_MODEL, verbose_name='Pracodawca'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruited_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Rekruter'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='requirements',
            field=models.TextField(max_length=300, verbose_name='Wymagania'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Oczekujące'), ('processing', 'W trakcie realizacji'), ('completed', 'Zakończone')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='jobrequeststatusupdate',
            name='job_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='requests.jobrequest', verbose_name='Aktualizacja statusu zapotrzebowania na pracę'),
        ),
        migrations.AlterField(
            model_name='jobrequeststatusupdate',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Wiadomość'),
        ),
        migrations.AlterField(
            model_name='jobrequeststatusupdate',
            name='new_status',
            field=models.CharField(choices=[('pending', 'Oczekujące'), ('processing', 'W trakcie realizacji'), ('completed', 'Zakończone')], max_length=20, verbose_name='Nowy status'),
        ),
        migrations.AlterField(
            model_name='jobrequeststatusupdate',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data aktualizacji'),
        ),
        migrations.AlterField(
            model_name='jobrequeststatusupdate',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Zaktualizowane przez'),
        ),
    ]
