"""
Django settings for kirismor project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see

https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from django.utils.translation import gettext_lazy as _

"""
Importowanie niezbędnych modułów:
- os: Moduł do interakcji z systemem operacyjnym.
- Path: Klasa z pathlib do obsługi ścieżek plików.
- gettext_lazy: Funkcja do tłumaczeń w aplikacjach Django.
"""

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

"""
BASE_DIR: Ścieżka bazowa projektu. Używana do budowania innych ścieżek w projekcie.
"""

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z7i3!2&)#_lwbao_ui23%ms259a%0=n8+ae=&hd3d*5^f0-j=6'

"""
SECRET_KEY: Klucz używany do zabezpieczania danych w aplikacji Django. Powinien być przechowywany w tajemnicy.
"""

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

"""
DEBUG: Flaga określająca, czy aplikacja działa w trybie debugowania. Nie powinna być używana w środowisku produkcyjnym.
"""

ALLOWED_HOSTS = []

"""
ALLOWED_HOSTS: Lista hostów, które są dozwolone do połączeń z aplikacją. Pusta lista oznacza, że wszystkie hosty są dozwolone.
"""

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'jobs',
    'requests',
    'news',
]

"""
INSTALLED_APPS: Lista zainstalowanych aplikacji w projekcie Django.
"""

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

"""
MIDDLEWARE: Lista middleware używanych w aplikacji Django.
"""

ROOT_URLCONF = 'kirismor.urls'

"""
ROOT_URLCONF: Konfiguracja głównych URLi dla projektu.
"""

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

"""
TEMPLATES: Konfiguracja systemu szablonów Django.
- BACKEND: Używany backend do renderowania szablonów.
- DIRS: Lista katalogów z szablonami.
- APP_DIRS: Czy szukać szablonów w katalogach aplikacji.
- OPTIONS: Dodatkowe opcje konfiguracji.
"""

WSGI_APPLICATION = 'kirismor.wsgi.application'

"""
WSGI_APPLICATION: WSGI aplikacja używana przez serwery do obsługi aplikacji Django.
"""

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

try:
    from kirismor.db_config import DATABASES
except ModuleNotFoundError:
    print("Brak konfiguracji bazy danych w pliku local_settings.py!")
    print("Uzupełnij dane i spróbuj ponownie!")
    exit(0)

"""
Konfiguracja bazy danych. Próba importu konfiguracji z pliku db_config.py.
"""

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

"""
AUTH_PASSWORD_VALIDATORS: Lista walidatorów haseł używanych w aplikacji.
"""

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'pl'

"""
LANGUAGE_CODE: Domyślny język używany w aplikacji.
"""

USE_L10N = False

"""
USE_L10N: Flaga określająca, czy używać lokalnych formatów daty, czasu itp.
"""

# Format settings
DATE_FORMAT = 'd-m-Y'
DATE_INPUT_FORMATS = ['%d-%m-%Y', '%d/%m/%Y']

"""
DATE_FORMAT: Domyślny format daty.
DATE_INPUT_FORMATS: Lista akceptowanych formatów daty przy wejściu.
"""

TIME_ZONE = 'Europe/Warsaw'

"""
TIME_ZONE: Domyślna strefa czasowa używana w aplikacji.
"""

USE_I18N = True

"""
USE_I18N: Flaga określająca, czy używać międzynarodowych funkcji tłumaczeń.
"""

USE_TZ = True

"""
USE_TZ: Flaga określająca, czy używać obsługi stref czasowych.
"""

LANGUAGES = [
    ('pl', _('Polski')),
    ('uk', _('Ukrainian')),
    ('ru', _('Russian')),
    ('en', _('English')),
    ('tr', _('Turkish')),
    ('de', _('German')),
    ('ka', _('Georgian')),
]

"""
LANGUAGES: Lista dostępnych języków w aplikacji.
"""

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'templates', 'locale'),
    os.path.join(BASE_DIR, 'accounts', 'locale'),
    os.path.join(BASE_DIR, 'jobs', 'locale'),
    os.path.join(BASE_DIR, 'requests', 'locale'),
    os.path.join(BASE_DIR, 'news', 'locale'),
]

"""
LOCALE_PATHS: Lista ścieżek do katalogów z plikami tłumaczeń.
"""

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

"""
STATIC_URL: URL do obsługi plików statycznych.
STATICFILES_DIRS: Lista katalogów z plikami statycznymi.
"""

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

"""
MEDIA_URL: URL do obsługi plików mediów.
MEDIA_ROOT: Katalog do przechowywania plików mediów.
"""

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

"""
DEFAULT_AUTO_FIELD: Domyślny typ pola klucza głównego dla modeli Django.
"""

AUTH_USER_MODEL = 'accounts.User'

"""
AUTH_USER_MODEL: Model użytkownika używany w aplikacji Django.
"""

LOGOUT_REDIRECT_URL = '/'

"""
LOGOUT_REDIRECT_URL: URL przekierowania po wylogowaniu użytkownika.
"""

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'sandbox.smtp.mailtrap.io'
EMAIL_PORT = 2525
EMAIL_USE_TLS = True
EMAIL_HOST_USER = '832219569f3daa'
EMAIL_HOST_PASSWORD = '306138df5c1dc8'

"""
Konfiguracja serwera poczty e-mail:
- EMAIL_BACKEND: Backend do obsługi poczty.
- EMAIL_HOST: Host serwera poczty.
- EMAIL_PORT: Port serwera poczty.
- EMAIL_USE_TLS: Używanie TLS do bezpiecznego połączenia.
- EMAIL_HOST_USER: Nazwa użytkownika serwera poczty.
- EMAIL_HOST_PASSWORD: Hasło użytkownika serwera poczty.
"""

# Site URL dla lokalnej dewelopmentu
SITE_URL = 'http://localhost:8000'

"""
SITE_URL: Adres URL witryny używany podczas lokalnej dewelopmentu.
"""
